// src/components/Navbar.vue
<template>
  <nav class="navbar container-fluid">
    <router-link to="/" class="navbar-brand">@glweems</router-link>
    <svg
      width="33.387"
      height="22.679"
      viewBox="0 0 33.387 22.679"
      class="menu-button"
      @click="toggleMenu"
    >
      <g transform="translate(128.5 23.811)">
        <line class="a" x2="33.387" transform="translate(-128.5 -21.811)"></line>
        <line class="a" x2="26" transform="translate(-121.5 -12.469)"></line>
        <line class="a" x2="33.387" transform="translate(-128.5 -3.132)"></line>
      </g>
    </svg>

    <transition
      enter-active-class="animated slideInDown faster"
      leave-active-class="bounceRight-leave"
    >
      <nav :class="[isOpen ? dropdown.activeClass : 'hidden']">
        <a
          v-for="link in links"
          :key="link.name"
          class="nav-link"
          @click="goToPage(link.path)"
        >{{ link.name }}</a>
      </nav>
    </transition>
  </nav>
</template>

<script>
export default {
  name: "Navbar",
  data() {
    return {
      isOpen: false,
      links: this.$router.options.routes,
      dropdown: {
        activeClass: "nav-links",
        errorClass: "hidden"
      }
    };
  },
  computed: {
    currentPage() {
      return this.$route.name;
    }
  },
  methods: {
    toggleMenu() {
      this.isOpen = !this.isOpen;
      console.log(this.isOpen);
    },
    goToPage(link) {
      this.isOpen = false;
      this.$router.push({ path: link });
    }
  }
};
</script>

<style lang="scss" scoped>
@import "@/scss/app.scss";
.navbar {
  // position: fixed;
  z-index: 2;
  top: 0;
  display: grid;
  grid-template-columns: 1fr auto;
  justify-content: space-between;
  // position: sticky;
  padding: 0.75rem 0.5rem;
  // background: color(bg);
}
.navbar-brand {
  align-self: center;
  @extend %heading;
  font-size: 26px;
  color: $primary;
}
.nav-link {
  @extend %heading;
  font-size: 26px;
  color: $primary;
  margin-bottom: 0.25rem;
}
.menu-button {
  text-align: right;
}
.nav-links {
  padding: 0.5rem 0;
  background: color(bg);
  grid-column: 1 / span 2;
  display: flex;
  // flex-direction: column;
  justify-content: flex-end;
  text-align: right;
  text-transform: uppercase;
}
.closed {
  .navlinks {
    display: none;
  }
}
button {
  text-align: right;
  margin: 0;
  padding: 0;
}
.nav-link:active {
  color: $secondary;
}
.menu-button {
  align-self: center;
  line {
    fill: none;
    stroke: color(secondary);
    stroke-width: 4px;
  }
}
.hidden {
  display: none;
}
</style>

// frontend/tutorials/react-peekaboo-navbar/src/Navbar.js
import React, { Component } from "react";
import PropTypes from "prop-types";
import styled from "styled-components";

export default class Navbar extends Component {
  static propTypes = {
    brand: PropTypes.shape({
      name: PropTypes.string.isRequired,
      to: PropTypes.string.isRequired
    }),
    links: PropTypes.arrayOf(
      PropTypes.shape({
        name: PropTypes.string.isRequired,
        to: PropTypes.string.isRequired
      })
    )
  };

  constructor(props) {
    super(props);
    this.state = {
      show: true,
      scrollPos: 0
    };
    this.handleScroll = this.handleScroll.bind(this);
  }

  componentDidMount() {
    window.addEventListener("scroll", this.handleScroll);
  }

  componentWillUnmount() {
    window.removeEventListener("scroll", this.handleScroll);
  }

  handleScroll() {
    const { scrollPos } = this.state;
    this.setState({
      scrollPos: document.body.getBoundingClientRect().top,
      show: document.body.getBoundingClientRect().top > scrollPos
    });
  }

  render() {
    const NavLinks = () =>
      this.props.links.map((link, index) => (
        <a key={index} href={link.to}>
          {link.name}
        </a>
      ));

    return (
      <Transition>
        <StyledNavbar className={this.state.show ? "active" : "hidden"}>
          <a className="brand" href={this.props.brand.to}>
            {this.props.brand.name}
          </a>
          <nav>
            <NavLinks />
          </nav>
        </StyledNavbar>
      </Transition>
    );
  }
}
const Transition = styled.div`
  .active {
    visibility: visible;
    transition: all 200ms ease-in;
  }
  .hidden {
    visibility: hidden;
    transition: all 200ms ease-out;
    transform: translate(0, -100%);
  }
`;
const StyledNavbar = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  margin: 0 auto;
  height: 3rem;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  font-weight: bolder;
  background: cornflowerblue;
  z-index: 1000;
  a {
    margin-right: 1rem;
    font-weight: normal;
    color: black;
    text-decoration: none;
  }
  .brand {
    font-style: italic;
    margin-left: 1rem;
    font-weight: bold;
    color: white;
    font-size: 1.25rem;
  }
`;
// const NavbarStyle = {
//   position: "fixed",
//   top: 0,
//   left: 0,
//   width: "100%",
//   margin: "0 auto",
//   padding: "0.5rem 0",
//   zIndex: 1000,
//   display: "flex",
//   flexDirection: "row",
//   justifyContent: "space-between",
//   alignContent: "center"
// };
